// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MGPOS.Data.MGPOSEntities;

public partial class Users
{
    public int UserID { get; set; }

    public string Username { get; set; }
}